Tambahkan path di web ui (done)
commMode dibuat dropdown di UI (done)
bisa download config.json di webui (done)
Mode ws, mqtt or, httppost, + failover ()
trigger pin output dari input ()
trigger Scheduler pin Output ()
Manual Control Output via WebUI (done)
buatkan web uploader ()
